config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :farmers
  resources :items
  get 'welcome/index'
  get '/mission', to: 'welcome#mission'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/login', to: 'farmers#log_in', as: 'log_in'
  get '/logout', to: 'farmers#log_out', as: 'log_out'
  post '/items/:id/add', to: 'items#add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    belongs_to :item
end

app/models/farmer.rb
class Farmer < ApplicationRecord
    has_secure_password
    validates :username, presence: true, length: 3..20, uniqueness: true
    validates :password, presence: true, length: 3..20
    validates :name, presence: true
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 }
    validates :value, presence: true, numericality: { greater_than: 0, less_than: 100 }
    validates :weight, presence: true, numericality: true, length: { in: 1..20 }
    validates :location, presence: true, length: { maximum: 30 }, uniqueness: true
    belongs_to :farmer
    has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  


  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_farmer, only: [:show, :edit, :update, :destroy]

  
  def index
    @farmers = Farmer.all
  end

  
  def show
  end

  
  def new
    @farmer = Farmer.new
  end

  
  def edit
  end

 
  def create
    @farmer = Farmer.new(farmer_params)
    
    respond_to do |format|
      if @farmer.save
        session[:farmer_id]=@farmer.id
        format.html { redirect_to items_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @farmer }
      else
        format.html { render :new }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  def log_in
    @farmer = Farmer.find_by(:username => params[:username])
    if @farmer && @farmer.authenticate(params[:password])
      session[:farmer_id]=@farmer.id
      flash[:notice] = "You have successfully logged in."
      redirect_to items_path
    else
      redirect_to new_farmer_path
    end
  end

  def update
    respond_to do |format|
      if @farmer.update(farmer_params)
        format.html { redirect_to @farmer, notice: 'Farmer was successfully updated.' }
        format.json { render :show, status: :ok, location: @farmer }
      else
        format.html { render :edit }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @farmer.destroy
    respond_to do |format|
      format.html { redirect_to farmers_url, notice: 'Farmer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def log_out
    session.clear
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

  private
   
    def set_farmer
      @farmer = Farmer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farmer_params
      params.require(:farmer).permit(:username, :name, :password)
    end
end

app/controllers/items_controller.rb
require 'pry'
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:new, :edit, :destroy]
  before_action :no_edit_or_destroy, only: [:edit, :destroy]
  
  def index
    @items = Item.all
    respond_to do |format|
      format.html 
      format.json {render json: @items}
    end

  end

  
  def show
    respond_to do |format|
      format.html 
      format.json {render json: @item}
    end

  end
  
  def new
    @item = Item.new
  end

  
  def edit
  end

# when there is an error in validation, how to add errors to the object
  def create
    @current_user = Farmer.find(session[:farmer_id]) if session[:farmer_id]
    if @current_user.items.create(item_params).valid?
      @current_user.items.create(item_params)
      flash[:notice] = 'Item was successfully created.'
      redirect_to items_path
      # begin
      #   @current_user.items.create!(item_params)
      # rescue ActiveRecord::RecordInvalid => invalid
      #   redirect_to new_item_path(invalid.record)
      # end
    else
      redirect_to new_item_path
    end
  end

  
  def update
    @current_user = Farmer.find(session[:farmer_id]) if session[:farmer_id]
    @current_user.items.find_by(id: params[:id]).update(item_params)
    flash[:notice] = 'Item was successfully updated.' 
     redirect_to items_path
  end


  def destroy
    @current_user = Farmer.find(session[:farmer_id]) if session[:farmer_id]
    @current_user.items.find_by(id: params[:id]).destroy
    flash[:notice] = 'Item was successfully destroyed.' 
    redirect_to items_path
  end

  def add
    @item = Item.find(params[:id])
    
    @comment = Comment.new(content: params[:content])
    @item.comments << @comment
    @comment.save
 
    # redirect_to item_path(@item)
  end


  private
    def check_user
      @current_user = Farmer.find(session[:farmer_id]) if session[:farmer_id]
      if @current_user == nil
        flash[:notice] = "Please log in or sign up."
        redirect_to items_path
      end
    end

    def no_edit_or_destroy
      @current_user = Farmer.find(session[:farmer_id]) if session[:farmer_id]
      if @current_user.items.find_by(id: params[:id]) == nil
        flash[:notice] = "Please edit or delete your own product"
        redirect_to items_path
      end
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :value, :weight, :location)
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def mission
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/farmers/_form.html.erb
<%= form_with(model: farmer, local: true) do |form| %>
  <% if farmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farmer.errors.count, "error") %> prohibited this farmer from being saved:</h2>

      <ul>
      <% farmer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/farmers/edit.html.erb
<h1>Editing Farmer</h1>

<%= render 'form', farmer: @farmer %>

<%= link_to 'Show', @farmer %> |
<%= link_to 'Back', farmers_path %>

app/views/farmers/index.html.erb
<h1>Farmers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farmers.each do |farmer| %>
      <tr>
        <td><%= farmer.username %></td>
        <td><%= farmer.name %></td>
        <td><%= farmer.password_digest %></td>
        <td><%= link_to 'Show', farmer %></td>
        <td><%= link_to 'Edit', edit_farmer_path(farmer) %></td>
        <td><%= link_to 'Destroy', farmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farmer', new_farmer_path %>

app/views/farmers/log_in.html.erb
<%-# Sign up -%>
<div class="container">

    <h1>Log in</h1>
        <%=form_for @farmer, controller: 'farmers', action: 'log_in' do |f| %>
                <div class="field">
                    <%= f.label :username %>
                    <%= f.text_field :username %>
                </div>

                <div class="field">
                    <%= f.label :password %>
                    <%= f.text_field :password %>
                </div>

            <%= f.submit "Sign Up" %>
        <%end%>
</div>
 

app/views/farmers/new.html.erb
<br/>
<br/>
<%-# Log in -%>
 <div class= "container">
    <div class = "row">
        <div class="col-6 ">
            <h1>Log in</h1>
            <%= form_tag(:action => "log_in", :method => "post") do %>
               <p>
                 <%= label_tag(:username) %>:
                 <%= text_field_tag(:username) %>
               </p>
               <p>
                 <%= label_tag(:password) %>:
                 <%= password_field_tag(:password) %>
               </p>
                 <%= submit_tag("Login") %>
               <% end %>
        </div>
     
  
 <%-# Sign up -%>
        <div class="col-6 ">
        <h1>Sign up</h1>
        <%= render 'form', farmer: @farmer %>
        </div>
    </div>
</div>
 <br>
<br>

app/views/farmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @farmer.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @farmer.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @farmer.password_digest %>
</p>

<%= link_to 'Edit', edit_farmer_path(@farmer) %> |
<%= link_to 'Back', farmers_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :value %><span> (Price/lb)</span>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :weight %><span> (Total product weight)</span>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<div id="comment-results">
</div>

<h1>Farmers Market</h1>
<br>
<table>
  <thead>
    <tr>
      <th class="right-margin">Product</th>
      <th class="right-margin">Price per Pound</th>
      <th class="right-margin">Total Available</th>
      <th class="right-margin">Source From</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name.capitalize %></td>
        <td class="center">$<%= number_with_precision(item.value, precision: 2) %></td>
        <td class="center"><%= item.weight %> lbs</td>
        <td><%= item.location.capitalize %></td>
        <td><%= link_to 'See', item%></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Find number of comments', item, class:"see" %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

<button id ="alpha">Alphabetize </button>
</div>

app/views/items/new.html.erb
<br>
<div class="container">
<h1>New Item</h1>

<%= render 'form', item: @item %>
<br>
<p>___________________</p>
<h5 id="calculator-heading"> Quick Calculator </h5>
<input type="text" id="grams" value=""></input><span>grams(g) = </span>
<input type="text" id="pounds"></input><span>pounds(lbs)</span>
<button id="calculate">Calculate</button>
<br>
<br>
<%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
<br>
<p id="notice"><%= notice %></p>
<div id="item-results">
</div>
<br>
<div class= "bg-secondary increase">
<p >
  <strong>Product:</strong>
  <%= @item.name.capitalize %>
</p>

<p>
  <strong>Price per pound:</strong>
  $<%= number_with_precision(@item.value, precision: 2)%>/lb
</p>

<p>
  <strong>Total Available:</strong>
  <%= @item.weight %> lbs
</p>

<p>
  <strong>Source:</strong>
  <%= @item.location %>
</p>
</div>
<div>
<button id="load-items">Load items</button>
</div>

<br>
<p class="text-info" id="comment-heading"> Comments </p>
<ul id="comment-list">
  <% @item.comments.each do |comment|%>
    <li class="comment"><%= comment.content%></li>
    <%end%>
</ul>


<%= form_tag("/items/#{@item.id}/add", method: "post", id: "add-comment") do %>
  <%= label_tag(:content, "") %>
  <%= text_area_tag(:content) %>
  <%= submit_tag("Add Comment") %>
<% end %>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <p class="navbar-brand" id="yellow">Farming</p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/"> Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/mission"> Our Mission </a>
      <a class="nav-item nav-link" href="/items"> Farmers Market </a>
      <a class="nav-item nav-link" id="sign-in" href="/farmers/new"> Sign in|Sign up </a>
      <a class="nav-item nav-link" id="log_out" href="/logout"> Log out </a>
      </div>
  </div>
</nav>

  <body>
    <%= yield %>
    <hr>

    <footer>
      <p>&copy; 2016 Farming, Inc.</p>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
</div>

<div class="jumbotron">
      <div class="container">
        <h1>Agriculture is </h1>
        <p>the cultivation of land and breeding of animals and plants to provide food, fiber, medicinal plants and other products to sustain and enhance life. Agriculture was the key development in the rise of sedentary human civilization, whereby farming of domesticated species created food surpluses that enabled people to live in cities. The study of agriculture is known as agricultural science. The history of agriculture dates back thousands of years; people gathered wild grains at least 105,000 years ago and began to plant them around 11,500 years ago before they became domesticated. Pigs, sheep, and cattle were domesticated over 10,000 years ago. Crops originate from at least 11 regions of the world. Industrial agriculture based on large-scale monoculture has in the past century come to dominate agricultural output, though about 2 billion people worldwide still depend on subsistence agriculture.</p>
        <p><a class="btn btn-primary btn-lg" target="_blank" href="https://en.wikipedia.org/wiki/Agriculture" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
<br>
<br>
    <div class="container">
    <%= image_tag("farms/farm.jpg", size: "900x450" , alt: "farmlands") %>
    <div>
<br>
<br>
<br>
    <h3 class="container" id="bigger">
    <%=link_to "Go See What Farmers Offer >>", items_path%>
    </h3>
<br>
<br>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Fruits & Vegetables</h2>
          <p>The subject of fruit and nut production deals with intensive culture of perennial plants, the fruits of which have economic significance (a nut is a fruit, botanically). It is one part of the broad subject of horticulture, which also encompasses vegetable growing and production of ornamentals and flowers.  </p>
          <%= image_tag("fruits_and_vegs/corn.jpg", height: "300", width: "350", alt: "rows of corn") %>
          <%= image_tag("fruits_and_vegs/grapes.jpg", height: "300", width: "350", alt: "rows of grapes") %>
        </div>
        <div class="col-md-4">
          <h2>Livestock</h2>
          <p>Livestock farming, raising of animals for use or for pleasure. In this article, the discussion of livestock includes both beef and dairy cattle, pigs, sheep, goats, horses, mules, asses, buffalo, and camels; the raising of birds commercially for meat or eggs (i.e., chickens, turkeys, ducks, geese, guinea fowl, and squabs) is treated separately. </p>
          <%= image_tag("livestock/cattle.jpg", height: "300", width: "350", alt: "roaming cattle in the sun") %>
          <%= image_tag("livestock/goats.jpg", height: "300", width: "350", alt: "roaming goats with a farmer") %>
       </div>
        <div class="col-md-4">
          <h2>Medicinal Plants</h2>
          <p>An herb farm is usually a farm where herbs are grown for market sale. Herbs may be for culinary, medicinal or aromatic use, and sold fresh-cut or dried. Herbs may also be grown for their essential oils or as raw material for making herbal products. </p>
          <%= image_tag("herbs/basil.jpg", height: "300", width: "350", alt: "some basil") %>
          <%= image_tag("herbs/chives.jpg", height: "300", width: "350", alt: "some chives") %>
        </div>
      </div>

    
</div>

app/views/welcome/mission.html.erb
<div class="container">
<br>
<h1 class="big"><strong> Our mission </strong></h1>
<br/>
<p id="mission">
<em>
Our mission is provide users with an updated market place that farmers use to distribute their goods. The secondary mission is to bring humans
closer to the land(Earth) and give thanks to farmers because we depend on farms. <b>No Farmers No Farms No Food.</b>
</em>
</p>
<br/>
<br/>
</div>
<div class = "container">
<%= image_tag("farms/agriculture.jpg", size: "900x450" , alt: "a farmer with delivering water to plants") %>
</div>
<br/>
<br/>
<div class="container">

<h2 class="big"><strong> Why farming </strong> </h2>
<br>
<strong>For decades, flavorful and rich produce and meat would end up on the dinner table after being tended to and closely monitored in the local farms.</strong></p>
<!--more-->
<p dir="ltr">Farming was not associated with commercialization and sparked images of rows of vegetables. Today, agriculture occurs on a much larger scale. Agriculture businesses grow food to distribute in mass quantities and at all points throughout the year - regardless of the food’s peak season. Additionally, agriculture now includes dairy and livestock among other characteristics. Agriculture at the most basic level is incredibly important for a number of reasons.</p>
<h3 dir="ltr"><strong>Raw Materials</strong></h3>
<p>Many raw materials depend directly on agriculture. Leading industries that use materials like cotton, sugar, tobacco, and oils are dependent on agriculture.</p>
<h3><strong>Jobs</strong></h3>
<p>Agriculture not only creates jobs for the farmers, it also provides jobs for the truck drivers who transport the produce to the store, grocery store employees who sell the goods, restaurant employees who receive the raw food, and many others.</p>
<h3><strong>Health Benefits</strong></h3>
<p>Like mom says, “eat your vegetables!” Multivitamins and supplements cannot compare to the vitamins and minerals that fresh fruits and vegetables provide for the body.</p>
<h3><strong>Foreign Exchange</strong></h3>
<p>Bananas, tea, coffee, tobacco, and spices contribute to and encourage a significant amount of foreign trade.</p>
<h3><strong>Connection to the Land</strong></h3>
<p>In many parts of the world, people depended on rain, rich soil, and the environment around them; farmers have a deep understanding and connection to nature.</p>
<p>While agriculture is important for a number of reasons, it is equally important for farmers and agriculture organizations to collect data. Having an understanding of the plant and &nbsp;to have an understanding of the type of plant that is being grown and a means to track the good, and bad, produce from seed to store. Utilize the Zerion platform in your workflow to&nbsp;make data collection more efficient.</p>
<p><a class="btn btn-default" target="_blank" href="https://blog.zerionsoftware.com/the-importance-of-farming" role="button">See blog &raquo;</a></p>
</div>
<br/>
<br/>